# Generated by Django 5.0.1 on 2024-02-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_autor_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidad',
        ),
    ]
